spring:
  data:
    rest:
      base-path: /api

loggin:
  level:
    domain: DEBUG

jwt:
  secret: a3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

---
spring:
  profiles: prod

logging:
  level:
    domain: WARN